input_select:
  guest_bedroom_light_mode:
    name: Guest Bedroom Scene Selector
    options:
      - Adaptive
      - Working
      - Dreamy Dusk
      - Honolulu
      - Lake Placid
      - Osaka
      - Rolling Hills
    initial: Adaptive
    icon: mdi:lightbulb

automation:
  ##############
  ## PRESENCE ##
  ##############

  - alias: Guest Bedroom - Turn On Lights on Motion Detection
    id: "guest_bedroom_lights_on_motion"
    description: "Turns on Guest Bedroom Lights when motion is detected and it's dark outside"
    trigger:
      - platform: state
        entity_id: binary_sensor.guest_bedroom_pir_sensor
        to: "on"
    condition:
      condition: and
      conditions:
        # 1. The room is either unoccupied or the mmwave sensor was triggered in the last 15 seconds. This is to avoid the cat triggering the lights as best as possible.
        - condition: template
          value_template: >
            {{ is_state('binary_sensor.guest_bedroom_occupancy', 'off') or
               (is_state('binary_sensor.guest_bedroom_occupancy', 'on') and
               (as_timestamp(now()) - as_timestamp(states.binary_sensor.guest_bedroom_mmwave_sensor.last_changed)) < 15) }}
        # 2. It's dark outside
        - condition: numeric_state
          entity_id: sensor.sunlight_pct
          below: 35
        # 3. The lights are off
        - condition: state
          entity_id: light.guest_bedroom
          state: "off"
        # 4. Sleep mode is currently set to Off
        - condition: template
          value_template: "{{ float(states('input_number.guest_bedroom_bedtime_status')) == 0.0 }}"
    action:
      # TODO: Set a sleep mode scene
      - action: light.turn_on
        entity_id: light.guest_bedroom

  - alias: Guest Bedroom - Turn On Lights When Dark and Occupied
    id: "guest_bedroom_lights_on_when_occupied"
    description: Turns on Guest Bedroom Lights when it is consistently dark and the room is already occupied
    trigger:
      - platform: time_pattern
        minutes: "/5"
      - platform: numeric_state
        entity_id: sensor.sunlight_pct
        below: 35
        for:
          minutes: 5
    condition:
      condition: and
      conditions:
        # 1. The room is occupied
        - condition: state
          entity_id: binary_sensor.guest_bedroom_occupancy
          state: "on"
        # 2. Lights are off
        - condition: state
          entity_id: light.guest_bedroom
          state: "off"
        # 3. It's dark outside
        - condition: numeric_state
          entity_id: sensor.sunlight_pct
          below: 35
        # 4. Sleep mode is currently set to Off
        - condition: template
          value_template: "{{ float(states('input_number.guest_bedroom_bedtime_status')) == 0.0 }}"
    action:
      # TODO: Set a sleep mode scene
      - action: light.turn_on
        entity_id: light.guest_bedroom

  - alias: Guest Bedroom - Turn Off Lights When Light Enough
    id: "guest_bedroom_lights_off_when_light_enough"
    description: Turns off Guest Bedroom Lights when it's consistently light enough
    trigger:
      - platform: time_pattern
        minutes: "/5"
      - platform: numeric_state
        entity_id: sensor.sunlight_pct
        above: 30
        for:
          minutes: 5
    condition:
      condition: and
      conditions:
        # 1. The lights are on
        - condition: state
          entity_id: light.guest_bedroom
          state: "on"
        # 2. The room is occupied
        - condition: state
          entity_id: binary_sensor.guest_bedroom_occupancy
          state: "on"
        # 3. The sunlight is above the threshold
        - condition: numeric_state
          entity_id: sensor.sunlight_pct
          above: 30
    action:
      - action: light.turn_off
        entity_id: light.guest_bedroom
        data:
          transition: 5

  - alias: Guest Bedroom - turn off lights when unoccupied
    id: "guest_bedroom_lights_off_when_unoccupied"
    description: Turns off Guest Bedroom Lights when occupancy is no longer detected
    trigger:
      - platform: state
        entity_id: binary_sensor.guest_bedroom_occupancy
        to: "off"
        for:
          minutes: 5
    condition:
      # 1. Sleep mode is currently set to Off
      - condition: template
        value_template: "{{ float(states('input_number.guest_bedroom_bedtime_status')) == 0.0 }}"
    action:
      - action: light.turn_off
        entity_id: light.guest_bedroom
        data:
          transition: 5

  ##############
  ##  DIMMER  ##
  ##############
  - alias: Guest Bedroom - Scene Cycle
    id: "guest_bedroom_scene_cycle"
    description: "Cycles through Guest Bedroom Scenes when Hue Switch 4 is pressed"
    trigger:
      - platform: event
        event_type: hue_event
        event_data:
          id: "guest_bedroom_dimmer_button"
          type: short_release
          subtype: 4
    action:
      - action: input_select.select_next
        entity_id: input_select.guest_bedroom_light_mode

  - alias: Guest Bedroom - Force Adaptive Lighting
    id: "guest_bedroom_force_adaptive_lighting"
    description: "Forces Adaptive Lighting in Guest Bedroom when Hue Switch 4 is pressed and held"
    trigger:
      - platform: event
        event_type: hue_event
        event_data:
          id: "guest_bedroom_dimmer_button"
          type: long_release
          subtype: 4
    action:
      - action: input_select.select_option
        entity_id: input_select.guest_bedroom_light_mode
        data:
          option: Adaptive

  - alias: Guest Bedroom - Scene Set
    id: "guest_bedroom_scene_set"
    description: "Sets the Guest Bedroom Scene when the Input Select is changed"
    trigger:
      - platform: state
        entity_id: input_select.guest_bedroom_light_mode
    action:
      - choose:
          - conditions:
              - condition: state
                entity_id: input_select.guest_bedroom_light_mode
                state: "Adaptive"
            sequence:
              - action: adaptive_lighting.set_manual_control
                data:
                  entity_id: switch.adaptive_lighting_guest_bedroom
                  manual_control: false

          - conditions:
              - condition: template
                value_template: "{{ not is_state('input_select.guest_bedroom_light_mode', 'Adaptive') }}"
            sequence:
              - action: scene.turn_on
                data_template:
                  entity_id: >
                    scene.guest_bedroom_{{ states('input_select.guest_bedroom_light_mode') | lower | replace(' ', '_') }}

  - alias: Guest Bedroom - Light Brightness up 5%
    id: "guest_bedroom_light_brightness_up"
    description: "Turns Guest Bedroom Lights brightness up 5% when Hue Switch 2 is pressed"
    trigger:
      - platform: event
        event_type: hue_event
        event_data:
          id: "guest_bedroom_dimmer_button"
          type: short_release
          subtype: 2
    action:
      - action: light.turn_on
        entity_id: light.guest_bedroom
        data:
          brightness_step_pct: 5

  - alias: Guest Bedroom - Light Brightness up continued
    id: "guest_bedroom_light_brightness_up_long"
    description: "Turns Guest Bedroom Lights brightness up 10% incrementally when Hue Switch 2 is pressed and held"
    trigger:
      - platform: event
        event_type: hue_event
        event_data:
          id: "guest_bedroom_dimmer_button"
          type: repeat
          subtype: 2
    action:
      - action: light.turn_on
        entity_id: light.guest_bedroom
        data:
          brightness_step_pct: 15

  - alias: Guest Bedroom - Light Brightness down 5%
    id: "guest_bedroom_light_brightness_down"
    description: "Turns Guest Bedroom Lights brightness down 5% when Hue Switch 3 is pressed"
    trigger:
      - platform: event
        event_type: hue_event
        event_data:
          id: "guest_bedroom_dimmer_button"
          type: short_release
          subtype: 3
    condition:
      - condition: state
        entity_id: light.guest_bedroom
        state: "on"
    action:
      - action: light.turn_on
        entity_id: light.guest_bedroom
        data:
          brightness_step_pct: -5

  - alias: Guest Bedroom - Light Brightness down continued
    id: "guest_bedroom_light_brightness_down_long"
    description: "Turns Guest Bedroom Lights brightness down 10% incrementally when Hue Switch 3 is pressed and held"
    trigger:
      - platform: event
        event_type: hue_event
        event_data:
          id: "guest_bedroom_dimmer_button"
          type: repeat
          subtype: 3
    condition:
      - condition: state
        entity_id: light.guest_bedroom
        state: "on"
    action:
      - action: light.turn_on
        entity_id: light.guest_bedroom
        data:
          brightness_step_pct: -15

  - alias: Guest Bedroom - Toggle lights
    id: "guest_bedroom_light_toggle"
    description: "Toggles Guest Bedroom Lights when Hue Switch 1 is pressed"
    trigger:
      - platform: event
        event_type: hue_event
        event_data:
          id: "guest_bedroom_dimmer_button"
          type: short_release
          subtype: 1
      - platform: event
        event_type: hue_event
        event_data:
          id: "guest_bedroom_dimmer_button"
          type: long_release
          subtype: 1
    action:
      - choose:
          - conditions:
              - condition: state
                entity_id: light.guest_bedroom
                state: "on"
            sequence:
              - action: light.turn_off
                entity_id: light.guest_bedroom
                data:
                  transition: 2
          - conditions:
              - condition: state
                entity_id: light.guest_bedroom
                state: "off"
            sequence:
              - action: light.turn_on
                entity_id: light.guest_bedroom
                data:
                  transition: 2
