homeassistant:
  packages: !include_dir_named packages

# Loads default set of integrations. Do not remove.
default_config:

# Text to speech
tts:
  - platform: google_translate

http:
  ip_ban_enabled: true
  login_attempts_threshold: 15
  use_x_forwarded_for: true
  trusted_proxies:
    - !secret trusted_proxy_1
    - !secret trusted_proxy_2
    - !secret trusted_proxy_3

history: !include inc/history.yaml
logbook: !include inc/logbook.yaml
logger:
  default: error