button_card_templates: !include_dir_merge_named "interface/cards/"

title: Canoe House

swipe_nav:
  animate: fade
  prevent_default: true
  swipe_amount: 10

views: !include_dir_merge_list "interface/views/"