# TODO: ADD GROUP MAN CAVE ALL WHICH INCLUDES CDS AND 3D PRINTER

scene:
  # TODO: ADD MAN CAVE CDS, but there was a werd browser issue
  - name: Man Cave Read
    entities:
      light.man_cave_colour:
        state: "on"
        xy_color: [0.505, 0.385]
        brightness: 255
        effect: None
      light.man_cave_lamp:
        state: "on"
        brightness: 255
        effect: None
      light.man_cave_cds:
        state: "off"
  - name: Man Cave Rest
    entities:
      light.man_cave_colour:
        state: "on"
        xy_color: [0.561, 0.4042]
        brightness: 90
        effect: None
      light.man_cave_lamp:
        state: "on"
        brightness: 90
        effect: None
      light.man_cave_cds:
        state: "off"
  - name: Man Cave Nightlight
    entities:
      light.man_cave_colour:
        state: "on"
        xy_color: [0.561, 0.4042]
        brightness: 1
        effect: None
      light.man_cave_lamp:
        state: "on"
        brightness: 1
        effect: None
      light.man_cave_cds:
        state: "off"
  - name: Man Cave Dreamy Dusk
    entities:
      light.man_cave_colour:
        state: "on"
        xy_color: [0.5493, 0.3702]
        brightness: 128
        effect: None
      light.man_cave_lamp:
        state: "on"
        brightness: 20
        effect: None
      light.man_cave_cds:
        state: "off"
      # light.man_cave_cds:
      #   state: "on"
      #   xy_color: [0.232, 0.084]
      #   brightness: 30
  - name: Man Cave Nebula
    entities:
      light.man_cave_colour:
        state: "on"
        xy_color: [0.2712, 0.1723]
        brightness: 61
        effect: None
      light.man_cave_lamp:
        state: "on"
        brightness: 20
        effect: None
      light.man_cave_cds:
        state: "off"
  - name: Man Cave Candlelight
    entities:
      light.man_cave_colour:
        state: "on"
        effect: candle
      light.man_cave_lamp:
        state: "on"
        effect: candle
      light.man_cave_cds:
        state: "off"

input_select:
  man_cave_light_mode:
    name: Man Cave Scene Selector
    options:
      - Adaptive
      - Read
      - Rest
      - Nightlight
      - Dreamy Dusk
      - Nebula
      - Candlelight
    initial: Adaptive
    icon: mdi:lightbulb

automation:
  - alias: Man Cave - Scene Cycle
    id: "1701536104"
    description: "Cycles through Man Cave Scenes when Hue Switch 3 is pressed"
    trigger:
      - platform: event
        event_type: hue_event
        event_data:
          id: "man_cave_switch_button"
          type: initial_press
          subtype: 3
    action:
      - service: input_select.select_next
        entity_id: input_select.man_cave_light_mode

  - alias: Man Cave - Scene Set
    id: "1701536104c"
    description: "Sets the Man Cave Scene when the Input Select is changed"
    trigger:
      - platform: state
        entity_id: input_select.man_cave_light_mode
    action:
      - choose:
          - conditions:
              - condition: state
                entity_id: input_select.man_cave_light_mode
                state: "Adaptive"
            sequence:
              - service: adaptive_lighting.set_manual_control
                data:
                  entity_id: switch.adaptive_lighting_man_cave
                  manual_control: false
              - service: light.turn_on
                data:
                  entity_id: light.man_cave_color
                  effect: None
              - service: light.turn_on
                data:
                  entity_id: light.man_cave_lamp
                  effect: None

          - conditions:
              - condition: template
                value_template: "{{ not is_state('input_select.man_cave_light_mode', 'Adaptive') }}"
            sequence:
              - service: scene.turn_on
                data_template:
                  entity_id: >
                    scene.man_cave_{{ states('input_select.man_cave_light_mode') | lower | replace(' ', '_') }}

  - alias: Man Cave - Light Brightness up 10%
    id: "1701536105"
    description: "Turns Man Cave Lights brightness up 10% when Hue Switch 4 is pressed"
    trigger:
      - platform: event
        event_type: hue_event
        event_data:
          id: "man_cave_switch_button"
          type: initial_press
          subtype: 4
    action:
      - service: light.turn_on
        entity_id: light.man_cave
        data:
          brightness_step_pct: 10

  - alias: Man Cave - Light Brightness down 10%
    id: "1701536106"
    description: "Turns Man Cave Lights brightness down 10% when Hue Switch 2 is pressed"
    trigger:
      - platform: event
        event_type: hue_event
        event_data:
          id: "man_cave_switch_button"
          type: initial_press
          subtype: 2
    condition:
      - condition: state
        entity_id: light.man_cave
        state: "on"
    action:
      - service: light.turn_on
        entity_id: light.man_cave
        data:
          brightness_step_pct: -10

  - alias: Man Cave - Toggle lights
    id: "1701536107"
    description: "Toggles Man Cave Lights on and off when Hue Switch 1 is pressed"
    trigger:
      - platform: event
        event_type: hue_event
        event_data:
          id: "man_cave_switch_button"
          type: initial_press
          subtype: 1
    action:
      - service: light.toggle
        entity_id: light.man_cave
