homeassistant:
  customize:
    person.matt:
      entity_picture: "/local/people/matt.png"
    person.sarah:
      entity_picture: "/local/people/sarah.png"

person:
  - name: Matt
    id: matt
    user_id: 96aa57047c3140719ded88983083d576
  - name: Sarah
    id: sarah
    user_id: a17a1b5a5d5c4bc0abe1b69c7f824259