homeassistant:
  customize:
    person.matt:
      entity_picture: "/local/people/matt.png"
    person.sarah:
      entity_picture: "/local/people/sarah.png"
    proximity.home:
      friendly_name: Proximity from Home
    proximity.matt_work:
      friendly_name: Proximity from Work (Matt)
    proximity.sarah_work:
      friendly_name: Proximity from Work (Sarah)

person:
  - name: Matt
    id: matt
    user_id: 96aa57047c3140719ded88983083d576
    device_trackers:
      - device_tracker.matts_iphone_app
      - device_tracker.matts_iphone_ip # Google WiFi Ping


  - name: Sarah
    id: sarah
    user_id: a17a1b5a5d5c4bc0abe1b69c7f824259
    device_trackers:
      - device_tracker.sarahs_iphone_app
      - device_tracker.sarahs_iphone_ip # Google WiFi Ping
