group:
  hallway_motion:
    name: "Hallway Motion"
    entities:
      - binary_sensor.hallway_motion_sensor_motion
      - binary_sensor.hallway_motion_sensor_2_motion

sensor:
  - platform: min_max
    name: "Hallway Illuminance"
    type: mean
    round_digits: 0
    entity_ids:
      - sensor.hallway_motion_sensor_illuminance
      - sensor.hallway_motion_sensor_2_illuminance

automation:
  - alias: Hallway - turn on lights
    id: "1676824317"
    description: "Turns on Hallway Lights when motion is detected"
    trigger:
      - platform: state
        entity_id: binary_sensor.hallway_motion_sensor_motion
        to: "on"
        # TODO: Only if it's dark
    condition:
      - condition: state
        entity_id: light.hallway
        state: "off"
    action:
      - service: light.turn_on
        entity_id: light.hallway

  - alias: Hallway - turn off lights
    id: "1676824318"
    description: "Turns off Hallway Lights when motion is no longer detected"
    trigger:
      - platform: state
        entity_id: group.hallway_motion
        to: "off"
    action:
      - service: light.turn_off
        entity_id: light.hallway
        data:
          transition: 5
# TODO: SHould make them be on always in the evening?
