group:
  landing_motion:
    name: "Landing Motion"
    entities:
      - binary_sensor.landing_motion_sensor_motion
      - binary_sensor.landing_motion_sensor_2_motion

sensor:
  - platform: min_max
    name: "Landing Illuminance"
    type: mean
    round_digits: 0
    entity_ids:
      - sensor.landing_motion_sensor_illuminance
      - sensor.landing_motion_sensor_2_illuminance

automation:
  - alias: Landing - turn on lights
    id: "1676824319"
    description: "Turns on Landing Lights when motion is detected"
    trigger:
      - platform: state
        entity_id: group.landing_motion
        to: "on"
        # TODO: Only if it's dark
    condition:
      - condition: state
        entity_id: light.landing
        state: "off"
    action:
      - service: light.turn_on
        entity_id: light.landing

  - alias: Landing - turn off lights
    id: "1676824320"
    description: "Turns off  Lights when motion is no longer detected"
    trigger:
      - platform: state
        entity_id: group.landing_motion
        to: "off"
    action:
      - service: light.turn_off
        entity_id: light.landing
        data:
          transition: 5
# TODO: SHould make them be on always in the evening?
