automation:
  - alias: Guest Bedroom - turn on lights
    id: "1701536290"
    description: "Turns on Guest Bedroom Lights when motion is detected"
    trigger:
      - platform: state
        entity_id: binary_sensor.guest_bedroom_occupancy
        to: "on"
        # TODO: Only if it's dark
        # TODO: What if room is already occupied?
    condition:
      condition: and
      conditions:
        # 1. The lights are not already on
        - condition: state
          entity_id: light.guest_bedroom
          state: "off"
        # TODO: Need a sleep mode for the room
        # 2. Sleep mode is not initialised
        # - condition: state
        #   entity_id: input_select.guest_bedroom_sleep_mode
        #   state: "Off"
    action:
      - service: light.turn_on
        entity_id: light.guest_bedroom

  # TODO: Nice if it has scenes - choose, if bedtime do X, otherwise do Y

  - alias: Guest Bedroom - turn off lights
    id: "1701536291"
    description: "Turns off Guest Bedroom Lights when occupancy is no longer detected"
    trigger:
      - platform: state
        entity_id: binary_sensor.guest_bedroom_occupancy
        to: "off"
        for:
          minutes: 5
    action:
      - service: light.turn_off
        entity_id: light.guest_bedroom
        data:
          transition: 5

  - alias: Guest Bedroom - turn on radiator
    id: "1701536292"
    description: "Turns on Guest Bedroom Radiator when occupancy is detected, with a temperature dependent on the time of day"
    trigger:
      - platform: time_pattern
        minutes: "/5"
      - platform: state
        entity_id: binary_sensor.guest_bedroom_occupancy
        to: "on"
    condition:
      condition: and
      conditions:
        # 1. The room is occupied
        - condition: state
          entity_id: binary_sensor.guest_bedroom_occupancy
          state: "on"
        # 2. It's cold outside
        # - condition: numeric_state
        #   entity_id: sensor.weatherbit_apparent_temperature
        #   below: 8
        # 3. The temperature in the room is lower than the target temperature
        - condition: template
          value_template: "{{ states('sensor.guest_bedroom_temperature') | float < states('sensor.bedroom_target_temperature') | float - 0.5 }}"
        # 4. The target temperature of the radiator does not already match the target temperature we want (prevents this automation running every 5 mins)
        - condition: template
          value_template: "{{ state_attr('climate.guest_bedroom', 'temperature') | float != states('sensor.bedroom_target_temperature') | float }}"
    action:
      - service: climate.set_temperature
        data_template:
          temperature: >
            {{ states('sensor.bedroom_target_temperature') | int }}
        target:
          entity_id: climate.guest_bedroom

  - alias: Guest Bedroom - turn off radiator
    id: "1701536293"
    description: "Turns off Guest Bedroom Radiator when occupancy is not detected for 10 minutes"
    trigger:
      - platform: state
        entity_id: binary_sensor.guest_bedroom_occupancy
        to: "off"
        for:
          minutes: 10
    action:
      - service: climate.set_temperature
        data_template:
          temperature: "{{ states('sensor.unoccupied_target_temperature') | int }}"
        target:
          entity_id: climate.guest_bedroom
