input_select:
  home_status:
    name: Home Status
    options:
      - Home
      - Away
      - Holiday
    initial: Home
    icon: mdi:home-account

automation:
  - alias: Home Status Change
    id: "1668931124"
    description: Toggles home status Home/Away based on the status of group.occupants
    trigger:
      - platform: state
        entity_id: group.occupants
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.home_status
          option: >
            {% if is_state('group.occupants', 'home') %}
              Home
            {% else %}
              Away
            {% endif %}
      - service: notify.mobile_app_matts_iphone
        data:
          title: Home Status Change
          message: >
            The home status has been changed to {{ states('input_select.home_status') }}

  - alias: "Home Status - Away Actions"
    id: "1669500012"
    description: "Runs actions when the home is set to Away mode"
    trigger:
      - platform: state
        entity_id: input_select.home_status
        to: "Away"
    action:
      - service: script.turn_on
        entity_id: script.turn_off_all_hardware
      # TODO: Check if needed to turn off rads, but the occupancy shpuld do that
      # - service: climate.set_temperature
      #   data:
      #     temperature: 8
      #   target:
      #     entity_id: climate.hive_thermostat
