automation:
  - alias: Nook - turn on lights
    id: "1701545500"
    description: "Turns on Nook Lights when motion is detected"
    trigger:
      - platform: state
        entity_id: binary_sensor.nook_occupancy
        to: "on"
        # TODO: Only if it's dark
        # TODO: What if room is already occupied?
    condition:
      - condition: state
        entity_id: light.nook
        state: "off"
    action:
      - service: light.turn_on
        entity_id: light.nook

  - alias: Nook - turn off lights
    id: "1701545501"
    description: "Turns off Nook Lights when occupancy is no longer detected"
    trigger:
      - platform: state
        entity_id: binary_sensor.nook_occupancy
        to: "off"
        for:
          minutes: 5
    action:
      - service: light.turn_off
        entity_id: light.nook
        data:
          transition: 5
