automation:
  - alias: Man Cave - Sleep Mode - Wind Down
    id: "1702244020"
    description: "Initialise Wind Down mode when motion is detected in the Man Cave between 20:30 and 03:00"
    trigger:
      # When either mmWave or PIR sensor are triggered (can't use binary_sensor.man_cave_occupancy as it might already be on)
      - platform: state
        entity_id: binary_sensor.man_cave_mmwave_sensor
        to: "on"
      - platform: state
        entity_id: binary_sensor.man_cave_pir_sensor
        to: "on"
    condition:
      condition: and
      conditions:
        # 1. Sleep mode is currently set to Off
        - condition: template
          value_template: "{{ float(states('input_number.man_cave_bedtime_status')) == 0.0 }}"
        # 2. It is between 20:30 and 03:00
        - condition: time
          after: "20:30:00"
          before: "03:00:00"
        # 3. There are guests staying in this room
        - condition: state
          entity_id: input_boolean.guests_staying_man_cave
          state: "on"
    action:
      - service: input_number.increment
        data:
          entity_id: input_number.man_cave_bedtime_status

  - alias: Man Cave - Sleep Mode - Asleep
    id: "1702244021"
    description: "Initialise Asleep mode when the lights are turned off in the Man Cave, when 'Wind Down' mode is active"
    trigger:
      - platform: state
        entity_id: light.man_cave
        to: "off"
    condition:
      # 1. Sleep mode is currently set to Wind Down
      - condition: template
        value_template: "{{ float(states('input_number.man_cave_bedtime_status')) == 1.0 }}"
    action:
      - service: input_number.increment
        data:
          entity_id: input_number.man_cave_bedtime_status

  - alias: Man Cave - Sleep Mode - Reset
    id: "1702244022"
    description: "Resets sleep mode when occupancy is not detected for 15 minutes in the Man Cave"
    trigger:
      - platform: state
        entity_id: binary_sensor.man_cave_occupancy
        to: "off"
        for:
          minutes: 15
    condition:
      # 1. Sleep mode is currently set to Wind Down or Asleep
      - condition: template
        value_template: "{{ float(states('input_number.man_cave_bedtime_status')) > 0.0 }}"
    action:
      - service: input_number.set_value
        data:
          entity_id: input_number.man_cave_bedtime_status
          value: 0.0
      - service: switch.turn_off
        entity_id: switch.adaptive_lighting_sleep_mode_man_cave
