# TARGET TEMPERATURES - USED IN AUTOMATIONS
sensor:
  - platform: template
    sensors:
      bedroom_target_temperature:
        friendly_name: "Target Temperature - Bedrooms"
        value_template: >
          {% if now().hour >= 21 or now().hour < 7 %}
            {% if states('sensor.pirateweather_apparent_temperature') | float < 2 %}
              14
            {% else %}
              12
            {% endif %}
          {% elif states('sensor.pirateweather_apparent_temperature') | float > 12 %}
            14
          {% elif states('sensor.pirateweather_apparent_temperature') | float > 6 %}
            16
          {% elif states('sensor.pirateweather_apparent_temperature') | float > 0 %}
            18
          {% elif states('sensor.pirateweather_apparent_temperature') | float <= 0 %}
            20
          {% else %}
            8
          {% endif %}
        unit_of_measurement: "°C"
      toilet_target_temperature:
        friendly_name: "Target Temperature - Toilet"
        value_template: >
          {% if states('sensor.pirateweather_apparent_temperature') | float > 6 %}
            14
          {% elif states('sensor.pirateweather_apparent_temperature') | float <= 6 %}
            16
          {% else %}
            8
          {% endif %}
        unit_of_measurement: "°C"
      bathroom_target_temperature:
        friendly_name: "Target Temperature - Bathrooms"
        value_template: >
          {% if states('sensor.pirateweather_apparent_temperature') | float > 12 %}
            14
          {% elif states('sensor.pirateweather_apparent_temperature') | float > 6 %}
            16
          {% elif states('sensor.pirateweather_apparent_temperature') | float <= 6 %}
            18
          {% else %}
            8
          {% endif %}
        unit_of_measurement: "°C"
      room_target_temperature:
        friendly_name: "Target Temperature - Rooms"
        value_template: >
          {% if (states('sensor.bedtime_status_total')  | int == states('sensor.total_bedrooms_in_use') | int * 2) %}
            10
          {% elif states('sensor.pirateweather_apparent_temperature') | float > 12 %}
            14
          {% elif states('sensor.pirateweather_apparent_temperature') | float > 6 %}
            16
          {% elif states('sensor.pirateweather_apparent_temperature') | float > 0 %}
            18
          {% elif states('sensor.pirateweather_apparent_temperature') | float <= 0 %}
            20
          {% else %}
            8
          {% endif %}
        unit_of_measurement: "°C"
      unoccupied_target_temperature:
        friendly_name: "Target Temperature - Rooms"
        value_template: 8
        unit_of_measurement: "°C"

      # TODO: Add in a boost if we are on our way home and its cold
