sensor:
  - platform: template
    sensors:
      lounge_temperature:
        friendly_name: "Lounge Temperature"
        value_template: "{{ state_attr('climate.lounge', 'current_temperature') }}"
        unit_of_measurement: "°C"
      lounge_target_temperature:
        friendly_name: "Lounge Target Temperature"
        value_template: "{{ state_attr('climate.lounge', 'temperature') }}"
        unit_of_measurement: "°C"
      dining_room_temperature:
        friendly_name: "Dining Room Temperature"
        value_template: "{{ state_attr('climate.dining_room', 'current_temperature') }}"
        unit_of_measurement: "°C"

automation:
  - alias: Lounge and Dining Room - turn on radiators
    id: "lounge_dining_room_radiator_on"
    description: "Turns on Lounge and Dining Room Radiators when occupancy is detected, with a temperature dependent on the time of day"
    trigger:
      - platform: time_pattern
        minutes: "/5"
      - platform: state
        entity_id: binary_sensor.lounge_occupancy
        to: "on"
    condition:
      condition: and
      conditions:
        # 1. The room is occupied
        - condition: state
          entity_id: binary_sensor.lounge_occupancy
          state: "on"
        # 2. The house is occupied - don't turn on if it's just the cat
        - condition: state
          entity_id: input_select.home_status
          state: "Home"
        # 3. The temperature in the room is lower than the target temperature
        - condition: or
          conditions:
            - condition: template
              value_template: "{{ states('sensor.lounge_temperature') | float < states('sensor.room_target_temperature') | float - 0.5 }}"
            - condition: template
              value_template: "{{ states('sensor.dining_room_temperature') | float < states('sensor.room_target_temperature') | float - 0.5 }}"
        # 4. The target temperature of the radiator does not already match the target temperature we want (prevents this automation running every 5 mins)
        - condition: template
          value_template: "{{ state_attr('climate.lounge', 'temperature') | float != states('sensor.room_target_temperature') | float }}"
        # TODO: Check that if the user manually adjusts, these dont then override it
    action:
      - action: climate.set_temperature
        data_template:
          temperature: "{{ states('sensor.room_target_temperature') | int }}"
        target:
          entity_id: climate.lounge
      - action: climate.set_temperature
        data_template:
          temperature: "{{ states('sensor.room_target_temperature') | int }}"
        target:
          entity_id: climate.dining_room

  - alias: Lounge and Dining Room - turn off radiators
    id: "lounge_dining_room_radiator_off"
    description: "Turns off Lounge and Dining Room Radiators when occupancy is not detected for 10 minutes"
    trigger:
      - platform: state
        entity_id: binary_sensor.lounge_occupancy
        to: "off"
        for:
          minutes: 10
    condition:
      # The target temperature does not already match the unoccupied target temperature we want
      - condition: template
        value_template: "{{ state_attr('climate.lounge', 'temperature') | float != states('sensor.unoccupied_target_temperature') | float }}"
    action:
      - action: climate.set_temperature
        data_template:
          temperature: "{{ states('sensor.unoccupied_target_temperature') | int }}"
        target:
          entity_id: climate.lounge
      - action: climate.set_temperature
        data_template:
          temperature: "{{ states('sensor.unoccupied_target_temperature') | int }}"
        target:
          entity_id: climate.dining_room
