sensor:
  - platform: template
    sensors:
      man_cave_temperature:
        friendly_name: "Man Cave Temperature"
        value_template: "{{ state_attr('climate.man_cave', 'current_temperature') }}"
        unit_of_measurement: "°C"
      man_cave_target_temperature:
        friendly_name: "Man Cave Target Temperature"
        value_template: "{{ state_attr('climate.man_cave', 'temperature') }}"
        unit_of_measurement: "°C"

automation:
  - alias: Man Cave - turn on radiator
    id: "man_cave_radiator_on"
    description: "Turns on Man Cave Radiator when occupancy is detected, with a temperature dependent on the time of day"
    trigger:
      - platform: time_pattern
        minutes: "/5"
      - platform: state
        entity_id: binary_sensor.man_cave_occupancy
        to: "on"
    condition:
      condition: and
      conditions:
        # 1. The room is occupied
        - condition: state
          entity_id: binary_sensor.man_cave_occupancy
          state: "on"
        # 2. The house is occupied - don't turn on if it's just the cat
        - condition: state
          entity_id: input_select.home_status
          state: "Home"
        # 3. The temperature in the room is lower than the target temperature by 0.5 degrees or higher than the target temperature by 0.5 degrees.
        # Otherwise the radiator will stay on a higher temperature than the target temperature, and the room will get too hot
        - condition: or
          conditions:
            - condition: template
              value_template: "{{ states('sensor.man_cave_temperature') | float < states('sensor.bedroom_target_temperature') | float - 0.5 }}"
            - condition: template
              value_template: "{{ states('sensor.man_cave_temperature') | float > states('sensor.bedroom_target_temperature') | float + 0.5 }}"
        # 4. The target temperature of the radiator does not already match the target temperature we want (prevents this automation running every 5 mins)
        - condition: template
          value_template: "{{ state_attr('climate.man_cave', 'temperature') | float != states('sensor.bedroom_target_temperature') | float }}"
    action:
      - action: climate.set_temperature
        data_template:
          temperature: "{{ states('sensor.bedroom_target_temperature') | int }}"
        target:
          entity_id: climate.man_cave

  - alias: Man Cave - turn off radiator
    id: "man_cave_radiator_off"
    description: "Turns off Man Cave Radiator when occupancy is not detected for 10 minutes"
    trigger:
      - platform: state
        entity_id: binary_sensor.man_cave_occupancy
        to: "off"
        for:
          minutes: 10
    condition:
      # The target temperature does not already match the unoccupied target temperature we want
      - condition: template
        value_template: "{{ state_attr('climate.man_cave', 'temperature') | float != states('sensor.unoccupied_target_temperature') | float }}"
    action:
      - action: climate.set_temperature
        data_template:
          temperature: "{{ states('sensor.unoccupied_target_temperature') | int }}"
        target:
          entity_id: climate.man_cave
