# @see https://valetudo.cloud/pages/integrations/home-assistant-integration.html#advanced-services
# @see https://www.home-assistant.io/integrations/script/#:~:text=To%20pass%20variables%20to%20the,%22%20action%3A%20service%3A%20script.
# @see https://www.home-assistant.io/integrations/mqtt/

homeassistant:
  customize:
    input_boolean.vacuum_kitchen:
      room_id: "16"
    input_boolean.vacuum_lounge:
      room_id: "18"
    input_boolean.vacuum_dining_room:
      room_id: "20"
    input_boolean.vacuum_nook:
      room_id: "19"
    input_boolean.vacuum_hallway:
      room_id: "17"

input_boolean:
  vacuum_kitchen:
    name: Kitchen
    icon: mdi:fridge
  vacuum_lounge:
    name: Lounge
    icon: mdi:sofa
  vacuum_dining_room:
    name: Dining Room
    icon: mdi:silverware-fork-knife
  vacuum_nook:
    name: Nook
    icon: mdi:rabbit
  vacuum_hallway:
    name: Hallway
    icon: mdi:stairs

group:
  vacuum_rooms:
    name: Vacuum Rooms
    entities:
      - input_boolean.vacuum_kitchen
      - input_boolean.vacuum_lounge
      - input_boolean.vacuum_nook
      - input_boolean.vacuum_hallway
      - input_boolean.vacuum_dining_room

script:
  vacuum_clean_segments:
    sequence:
      - service: script.turn_on
        target:
          entity_id: script.vacuum_clean_segments_message
        data:
          variables:
            segments:
              '{{expand("group.vacuum_rooms") | selectattr("state","eq","on")
              | map(attribute="attributes.room_id") | list | to_json}}'
    mode: single
    alias: vacuum_clean_segments
    icon: mdi:arrow-right
  vacuum_clean_segments_message:
    alias: vacuum_clean_segments_message
    sequence:
      - service: mqtt.publish
        data:
          topic: valetudo/roborock/MapSegmentationCapability/clean/set
          payload_template: '{"segment_ids": {{segments}},"iterations": {{ iterations }}}'
    mode: single
