binary_sensor:
  - platform: template
    sensors:
      3d_printer_printing:
        friendly_name: "3D Printer Printing"
        value_template: "{{ states('sensor.3d_printer_power')|float(0) > 20 }}"
        device_class: power
        icon_template: >-
          {% if states('sensor.3d_printer_power')|float(0) > 20 %}
            mdi:power-plug
          {% else %}
            mdi:power-plug-off
          {% endif %}

automation:
  - alias: 3D Printer - Printing Complete
    id: "1697392923"
    description: "Turns off the 3D Printer when the plug has been idle for 15 mins, and sends a notification to anyone who is home."
    trigger:
      - platform: state
        entity_id: binary_sensor.3d_printer_printing
        to: "off"
        for:
          minutes: 15
    action:
      - service: switch.turn_off
        entity_id: switch.3d_printer
      - service: script.notify_engine
        data:
          notify_title: "Printing Complete"
          notify_message: "Your shiny new 3D print is complete - enjoy!"
