sensor:
  - platform: rest
    resource: !secret json_bins
    method: GET
    name: Bin Collection
    value_template: "{{ value_json.data.rows[0].DomesticBinDay }}"
    scan_interval: 7200 # Every Two Hours

template:
  - sensor:
      - name: "Next Bin Collection"
        unit_of_measurement: "Days"
        state: >
          {% set next_bins_string = states('sensor.bin_collection') %}
          {%- for item in next_bins_string.split('Collections are ') %}
            {%- if loop.index  != 1 %}
              {% set date = item.split(' ')[0] %}
              {% if date == 'today' %}
                0
              {% else %}
                {% set date_parts = date.split('/') %}
                {% set date = date_parts[2] + "-" + date_parts[1] + "-" + date_parts[0] + "T07:30:00+00:00" %}
                {% set duedate = as_timestamp(date[0:4] ~ "-" ~ date[5:7] ~ "-" ~ date[8:10] ~ date[10:18]) %}
                {% set currentdate = now().timestamp() %}
                {% set seconds =  duedate - currentdate  %}
                {{(seconds / 86400)|round(0,'ceil')}}
              {% endif %}
            {%- endif %}
          {%- endfor %}
        attributes:
          type: >
            {% set next_bins_string = states('sensor.bin_collection') %}
            {%- for item in next_bins_string.split('Collections are ') %}
              {%- if loop.index  != 1 %}
                {{ item.split(' ')[1]|replace(")", "")|replace("(", "") }}
              {%- endif %}
            {%- endfor %}
          next_collection_date: >
            {% set next_bins_string = states('sensor.bin_collection') %}
            {%- for item in next_bins_string.split('Collections are ') %}
              {%- if loop.index  != 1 %}
              {% set date = item.split(' ')[0] %}
                {% if date == 'today' %}
                  {{ now().day }}/{{ now().month }}/{{ now().year }}
                {% else %}
                  {% set date_parts = date.split('/') %}
                  {% set date = date_parts[2] + "-" + date_parts[1] + "-" + date_parts[0] + "T07:30:00+00:00" %}
                  {{ date }}
                {% endif %}
              {%- endif %}
            {%- endfor %}
