homeassistant:
  customize:
    person.matt:
      notifier: notify.mobile_app_matts_iphone
      entity_picture: "/local/people/matt.png"
    person.sarah:
      notifier: notify.mobile_app_sarahs_iphone
      entity_picture: "/local/people/sarah.png"
    proximity.home:
      friendly_name: Proximity from Home
    proximity.matt_work:
      friendly_name: Proximity from Work (Matt)
    proximity.sarah_work:
      friendly_name: Proximity from Work (Sarah)

person:
  - name: Matt
    id: matt
    user_id: 96aa57047c3140719ded88983083d576
    device_trackers:
      - device_tracker.matts_iphone_app
      - device_tracker.matts_iphone_ip # Google WiFi Ping

  - name: Sarah
    id: sarah
    user_id: a17a1b5a5d5c4bc0abe1b69c7f824259
    device_trackers:
      - device_tracker.sarahs_iphone_app
      - device_tracker.sarahs_iphone_ip # Google WiFi Ping

group:
  occupants:
    name: Occupants
    entities:
      - person.matt
      - person.sarah
  friends:
    name: Friends
    entities:
      - device_tracker.katts_phone
  guests:
    name: Guests
    entities:
      - group.friends
      #- group.family

proximity:
  matt_from_home:
    zone: home
    tolerance: 50
    unit_of_measurement: mi
    devices: person.matt
  sarah_from_home:
    zone: home
    tolerance: 50
    unit_of_measurement: mi
    devices: person.sarah

sensor:
  - platform: template
    sensors:
      # people_home:
      #   friendly_name: People Home
      #   value_template: >-
      #     {{ states.person | selectattr( 'state', 'eq', 'home') | list | length }}

      matt_friendly_location:
        friendly_name: Matt Friendly Location
        value_template: >
          {% if states.person.matt.state == 'home' %}
          Home
          {% elif (states.proximity.matt_from_home.state|float >= 70) and (states.proximity.matt_from_home.state|float <= 200) %}
          Lost
          {% elif states.proximity.matt_from_home.state|float > 200 %}
          Far Away
          {% elif states.person.matt.state == 'Matt Work' %}
          Work
          {% else %}
          nr. {{states.sensor.matts_iphone_geocoded_location.attributes.Thoroughfare}}
          {% endif %}

      sarah_friendly_location:
        friendly_name: Sarah Friendly Location
        value_template: >
          {% if states.person.sarah.state == 'home' %}
          Home
          {% elif (states.proximity.sarah_from_home.state|float >= 70) and (states.proximity.sarah_from_home.state|float <= 200) %}
          Lost
          {% elif states.proximity.sarah_from_home.state|float > 200 %}
          Far Away
          {% elif states.person.sarah.state == 'Sarah Work' %}
          Work
          {% else %}
          nr. {{states.sensor.sarahs_iphone_geocoded_location.attributes.Thoroughfare}}
          {% endif %}
