automation:
  - alias: Theme Switch
    id: '1670076634'
    description: Switches the Home Assistant theme based on whether the sun is above the horizon
    trigger:
      - platform: state
        entity_id: sun.sun
    action:
      - choose:
        - conditions:
          - condition: state
            entity_id: sun.sun
            state: "above_horizon"
          sequence:
          - service: frontend.set_theme
            data:
              name: minimalist-desktop
              mode: light
        - conditions:
          - condition: state
            entity_id: sun.sun
            state: "below_horizon"
          sequence:
          - service: frontend.set_theme
            data:
              name: minimalist-desktop
              mode: dark